# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx2G
# Ooops, OOM because of that
org.gradle.daemon=false

minecraft_version=1.7.10
forge_version=10.13.4.1614-1.7.10
mod_version=0.0.3
mod_identifier=stare-of-doom

unimixins_version=0.1.14
accessTransformersFile = stare-of-doom_at.cfg